### ISSUE TITLE
Amazon ElastiCache Cluster Client

### ISSUE THREAD

**Issue by petk** [php-earth/alpine#1]
TODO:

* [ ] Add [Amazon ElastiCache Cluster Client](https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php) thanks to @mclueppers

https://github.com/mclueppers/alpine/blob/master/build/v3.7/php7.2-memcached-elasticache/APKBUILD

**Comment by mclueppers** [comment]
You're welcome Peter. Just one more thing, you'd need https://github.com/mclueppers/alpine/tree/master/build/v3.7/libmemcached-elasticache in order to build the extension. 
Amazon's Auto Discovery is backwards compatible with the original Memcached extension yet the library is where it's being implemented.

**Comment by petk** [comment]
Hello, I've checked this one... I'm not in favour of having such good forks of extensions that are forgotten and missed for the other people searching for PHP extensions. Do you think there is any option to move such fork of extension to the PECL directly? What is needed to get this done?

**Comment by mclueppers** [comment]
I had a look recently at this extension - it seems it's a dead project now with last commits from more than 2 years ago. It's not able to build for Alpine 3.9 and PHP 7.3 and I don't have the time to even try to create a patch so it works. AFAIK majority of users, myself included, use now Redis when they plan to deploy in AWS.

**Comment by petk** [comment]
Thanks for the info... Ok, Redis sounds like a good replacement if everything works as was with this extension. I think so too. Closing as resolved.  Thank you.
