### ISSUE TITLE
phpearth.rsa.pub missing from website

### ISSUE THREAD

**Issue by dittto** [php-earth/alpine#14]
Hi,

Not sure if it's a bug with this repo or the release process but the file https://repos.php.earth/alpine/phpearth.rsa.pub is missing.

**Comment by petk** [comment]
Confirmed. Will be resolved later today. Thank you for reporting this..

**Comment by emrecanozkok** [comment]
still continuing,i cant run pipeline for product deployment.shit.

**Comment by dittto** [comment]
Thanks @petk !

My hack for now is:

```
- ADD             https://repos.php.earth/alpine/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub
+ ADD             https://raw.githubusercontent.com/phpearth/alpine/master/public/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub
```

:)

**Comment by emrecanozkok** [comment]
> Thanks @petk !
> 
> My hack for now is:
> 
> ```
> - ADD             https://repos.php.earth/alpine/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub
> + ADD             https://raw.githubusercontent.com/phpearth/alpine/master/public/phpearth.rsa.pub /etc/apk/keys/phpearth.rsa.pub
> ```
> :)

thank you bro.

**Comment by petk** [comment]
And fixed! Cheers.
