### ISSUE TITLE
PHP 7.3 / Imagick not working

### ISSUE THREAD

**Issue by temp** [php-earth/alpine#15]
After installing php7.3-imagick php throws errors:
```
# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: /usr/lib/php/7.3/modules/imagick (Error loading shared library /usr/lib/php/7.3/modules/imagick: No such file or directory), /usr/lib/php/7.3/modules/imagick.so (Error relocating /usr/lib/php/7.3/modules/imagick.so: _rc_dtor_func: symbol not found)) in Unknown on line 0
PHP 7.3.0 (cli) (built: Dec  6 2018 15:50:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
``` 

Seems like php7.3-imagick is rather old (is not not being built automatically?)
```
php7.3-7.3.0-r10 x86_64 {php7.3} (PHP-3 BSD LGPL2 MIT Zend) [installed]
php7.3-imagick-3.4.3-r0 x86_64 {php7.3-imagick} (PHP-3) [installed]
```
Base php is r10, imagick is r0.

**Comment by temp** [comment]
Building the imagick extension manually and replacing the provided imagick.so works fine, so it shouldn't be a general problem. Maybe the package just has to be rebuilt?

**Comment by petk** [comment]
Hello, the PECL imagick extension is of version that is available via PECL: https://pecl.php.net/package/imagick

Yes, it does look like some sort of bug on the PHP-7.3... 

Thanks for reporting.

**Comment by petk** [comment]
Has been resolved.
