### ISSUE TITLE
inconsistency with php packages

### ISSUE THREAD

**Issue by glensc** [php-earth/alpine#25]
1. why is that 7.2 and 7.2 have provides line, but 7.1 does not?

```diff
@@ -346,6 +349,7 @@

 package() {
   install="$pkgname.post-install"
+  provides="php=$pkgver-r$pkgrel php7=$pkgver-r$pkgrel"
   replaces="php php7"

   cd "$builddir"
```

2. why fpm post install does different trickery among versions.
  - 7.1 checks for php-fpm7.2 & php-fpm7.3
  - 7.2 checks for php-fpm7.3
  - 7.3 does not check anything

as a result of these, 7.1 and 7.3 can be installed in parallel, while 7.2 cann not be installed in parallel with any version.

i don't think there should be conflicts between the packages, should allow installing any version in parallel, and symlinks to unversioned paths could left undefined, i.e probably last install will win.

**Comment by petk** [comment]
Those should be probably moved to PHP 7.3 now... These were used to override accidental cases of installing upstream php7-* and php-* packages.

**Comment by glensc** [comment]
in my opinion the all variants should have identical behaviour. either of:
1. do not "provide", "replace" anything - all they do not place same files ... OR
2. they all must fight with each other: "replace" all other versions, all combinations

I would go for "1." because it's simple and straight forward. there's no reason why can't install in parallel 7.1 and 7.3 packages.

the packages are mostly installed to containers, so if something goes wrong, try again and commit proper change.

btw, https://github.com/codecasts/php-alpine uses repo pinning technology:
```dockerfile
# add the repository, make sure you replace the correct versions if you want.
RUN echo "@php https://dl.bintray.com/php-alpine/v3.9/php-7.3" >> /etc/apk/repositories

# install php and some extensions
# notice the @php is required to avoid getting default php packages from alpine instead.
RUN apk add --update php@php
RUN apk add --update php-mbstring@php
```

it might be a solution to your problem. I personally don't like it, and it seems to have some issues. it's either due to apk bugs, or people don't understand how the repo pinning actually works:
- https://github.com/codecasts/php-alpine/issues/72
