### ISSUE TITLE
Repo for Alpine 3.8?

### ISSUE THREAD

**Issue by Foddy** [php-earth/alpine#3]
Thank you very much for this awesome PHP repo. A few weeks ago Alpine 3.8 released and I wonder if you are planning to release a 3.8 branch of the PHP.earth Alpine repo?

**Comment by petk** [comment]
Repository for Alpine v3.8 has been added:

```bash
apk add --no-cache wget ca-certificates \
&& wget -O /etc/apk/keys/phpearth.rsa.pub https://repos.php.earth/alpine/phpearth.rsa.pub \
&& echo "https://repos.php.earth/alpine/v3.8" >> /etc/apk/repositories
```

It includes PHP 7.1, 7.2, and upcoming unstable 7.3 version.
