### ISSUE TITLE
certificate error for repos.php.earth

### ISSUE THREAD

**Issue by vtotare** [php-earth/alpine#32]
Hi Team,
I am using below approach on Alpine linux to build my PHP container.

**Approach:**
apk add --no-cache wget ca-certificates \
&& wget -O /etc/apk/keys/phpearth.rsa.pub https://repos.php.earth/alpine/phpearth.rsa.pub \
&& echo "https://repos.php.earth/alpine/v3.8" >> /etc/apk/repositories

However, I started receiving below error since yesterday while building docker container. Can you please help me on this and what is this issue. I am not getting this error while accessing site in browser.

**Error:**
#9 4.239 fetch https://repos.php.earth/alpine/v3.8/x86_64/APKINDEX.tar.gz
#9 4.530 139816800693196:error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed:ssl_clnt.c:1132:
#9 4.533 ERROR: https://repos.php.earth/alpine/v3.8: Permission denied
#9 4.533 WARNING: Ignoring https://repos.php.earth/alpine/v3.8: No such file or directory

**Comment by Maikuolan** [comment]
*Cross-referencing due to related: phpearth/PHP.earth#37*
*Cross-referencing due to related: phpearth/docker-php#56*

**Comment by vtotare** [comment]
@Maikuolan :
Can you please let me know that why i am suddenly started getting this error.

**Comment by Maikuolan** [comment]
*Tagging @petk for review.*

(I'm a newbie to alpine, don't know the details about the certificate, and AFAIK, all the work at this repo was kindly put together by @petk. So possibly, he may have a better idea about what's going on here).

**Comment by vtotare** [comment]
@Maikuolan: 
Thanks for your response !
I am totally blocked just because of this unexpeted error and tried various way including suggested in forum - https://docs.php.earth/linux/alpine/  but no luck, hence seeking help from team.

**Comment by vtotare** [comment]
@petk : 
Your assistance will really help me to get rid of this issue. I know that its public forum and should not be hurry to get solution but it was working till yesterday and now suddenly stopped, cause unable to proceed further

**Comment by lvidal1** [comment]
Did anyone find a solution to this? This is weird as It was workjing very well a couple days ago. I am getting a similar error.

```
#6 1.414 140540927331276:error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed:ssl_clnt.c:1026:
#6 1.417 WARNING: Ignoring https://repos.php.earth/alpine/v3.7/x86_64/APKINDEX.tar.gz: Permission denied
```

As @vtotare mentioned, please @petk, any help on this will be appreciated.

**Comment by fpalamour** [comment]
It probably has something to do with the DST Root CA X3 certificate expiration. I found this repo for a possible replacement solution but haven't tried it yet https://github.com/codecasts/php-alpine
