### ISSUE TITLE
https://repos.php.earth/alpine is offline

### ISSUE THREAD

**Issue by good2207** [php-earth/alpine#33]
It seems that the same issue as the existing issue has occurred.
 https://github.com/phpearth/alpine/issues/28 

https://repos.php.earth/alpine is not reachable now.
Are there some alternative to add to my dockerfile?

Please recover quickly.

Thanks a lot. 

cc @petk

**Comment by troussema** [comment]
+1

**Comment by troussema** [comment]
try : https://github.com/codecasts/php-alpine

**Comment by petk** [comment]
Hello, yes these Alpine repos have been shut down in favor of the official Alpine repository. Also, please upgrade your PHP. These repos use only up to very outdated PHP 7.4. Thanks.
