### ISSUE TITLE
Memcached for PHP 7.3

### ISSUE THREAD

**Issue by petk** [php-earth/alpine#4]
Currently Memcached on PHP 7.3 can't be built yet.

**Comment by Foddy** [comment]
I agree with that. php7.3-mcrypt is also failing.

**Comment by petk** [comment]
Has been updated.


> I agree with that. php7.3-mcrypt is also failing.

Mcrypt now works for PHP 7.3 also. But it's not included in these packages nor recommended to use anymore. It can be installed via PECL command line script, however please migrate to sodium which is built into PHP 7.3 directly.
