### ISSUE TITLE
PHP7.3RC2 Released ;-) 

### ISSUE THREAD

**Issue by PhilETaylor** [php-earth/alpine#9]
nudge nudge ;)

**Comment by PhilETaylor** [comment]
one of the reasons I'm using this repo was to test the bleeding edge Release candidates with timely builds.

It's been over a week now since RC2 was released.

Im more than happy to contribute, to help speed things up - but I find no build instructions for the packaging and it seems issues are being ignored. 

Is there someway we can contribute to this project so that it can respond faster to these releases?

**Comment by petk** [comment]
Hello, contributing to this particular repository is not a normal procedure because it requires building the PHP (takes hardware resources and time) and uploading files online... So, hopefully it will be built soon....

**Comment by PhilETaylor** [comment]
Thanks for the Sunday afternoon reply. Im guessing a lot of the process could be automated right?

**Comment by petk** [comment]
PHP 7.3.0 RC2 and now RC3 has been added in the repo.

**Comment by PhilETaylor** [comment]
Thank you :) Really appreciate it :)
